apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <Cluster-CA-Data>
    server: <Cluster-URL>
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: oidc
  name: oidc@kubernetes
current-context: oidc@kubernetes
kind: Config
preferences: {}
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=<terraform-output>
      - --oidc-client-id=<terraform-output>
      - --oidc-extra-scope=email offline_access profile openid
      command: kubectl
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
